// <copyright file="FraudCheckResult.cs" company="APIMatic">
// Copyright (c) APIMatic. All rights reserved.
// </copyright>
namespace AdyenMergedAPI.Standard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using APIMatic.Core.Utilities.Converters;
    using AdyenMergedAPI.Standard;
    using AdyenMergedAPI.Standard.Utilities;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// FraudCheckResult.
    /// </summary>
    public class FraudCheckResult
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FraudCheckResult"/> class.
        /// </summary>
        public FraudCheckResult()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FraudCheckResult"/> class.
        /// </summary>
        /// <param name="accountScore">accountScore.</param>
        /// <param name="checkId">checkId.</param>
        /// <param name="name">name.</param>
        public FraudCheckResult(
            int accountScore,
            int checkId,
            string name)
        {
            this.AccountScore = accountScore;
            this.CheckId = checkId;
            this.Name = name;
        }

        /// <summary>
        /// The fraud score generated by the risk check.
        /// </summary>
        [JsonProperty("accountScore")]
        public int AccountScore { get; set; }

        /// <summary>
        /// The ID of the risk check.
        /// </summary>
        [JsonProperty("checkId")]
        public int CheckId { get; set; }

        /// <summary>
        /// The name of the risk check.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"FraudCheckResult : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }
            return obj is FraudCheckResult other &&                this.AccountScore.Equals(other.AccountScore) &&
                this.CheckId.Equals(other.CheckId) &&
                ((this.Name == null && other.Name == null) || (this.Name?.Equals(other.Name) == true));
        }
        
        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"this.AccountScore = {this.AccountScore}");
            toStringOutput.Add($"this.CheckId = {this.CheckId}");
            toStringOutput.Add($"this.Name = {(this.Name == null ? "null" : this.Name)}");
        }
    }
}