// <copyright file="ThreeDS1Result2.cs" company="APIMatic">
// Copyright (c) APIMatic. All rights reserved.
// </copyright>
namespace AdyenMergedAPI.Standard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using APIMatic.Core.Utilities.Converters;
    using AdyenMergedAPI.Standard;
    using AdyenMergedAPI.Standard.Utilities;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// ThreeDS1Result2.
    /// </summary>
    public class ThreeDS1Result2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDS1Result2"/> class.
        /// </summary>
        public ThreeDS1Result2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDS1Result2"/> class.
        /// </summary>
        /// <param name="cavv">cavv.</param>
        /// <param name="cavvAlgorithm">cavvAlgorithm.</param>
        /// <param name="eci">eci.</param>
        /// <param name="threeDAuthenticatedResponse">threeDAuthenticatedResponse.</param>
        /// <param name="threeDOfferedResponse">threeDOfferedResponse.</param>
        /// <param name="xid">xid.</param>
        public ThreeDS1Result2(
            string cavv = null,
            string cavvAlgorithm = null,
            string eci = null,
            string threeDAuthenticatedResponse = null,
            string threeDOfferedResponse = null,
            string xid = null)
        {
            this.Cavv = cavv;
            this.CavvAlgorithm = cavvAlgorithm;
            this.Eci = eci;
            this.ThreeDAuthenticatedResponse = threeDAuthenticatedResponse;
            this.ThreeDOfferedResponse = threeDOfferedResponse;
            this.Xid = xid;
        }

        /// <summary>
        /// The cardholder authentication value (base64 encoded).
        /// </summary>
        [JsonProperty("cavv", NullValueHandling = NullValueHandling.Ignore)]
        public string Cavv { get; set; }

        /// <summary>
        /// The CAVV algorithm used.
        /// </summary>
        [JsonProperty("cavvAlgorithm", NullValueHandling = NullValueHandling.Ignore)]
        public string CavvAlgorithm { get; set; }

        /// <summary>
        /// 3D Secure Electronic Commerce Indicator (ECI).
        /// </summary>
        [JsonProperty("eci", NullValueHandling = NullValueHandling.Ignore)]
        public string Eci { get; set; }

        /// <summary>
        /// The authentication response from the ACS.
        /// </summary>
        [JsonProperty("threeDAuthenticatedResponse", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDAuthenticatedResponse { get; set; }

        /// <summary>
        /// Whether 3D Secure was offered or not.
        /// </summary>
        [JsonProperty("threeDOfferedResponse", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDOfferedResponse { get; set; }

        /// <summary>
        /// A unique transaction identifier generated by the MPI on behalf of the merchant to identify the 3D Secure transaction, in `Base64` encoding.
        /// </summary>
        [JsonProperty("xid", NullValueHandling = NullValueHandling.Ignore)]
        public string Xid { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();

            this.ToString(toStringOutput);

            return $"ThreeDS1Result2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (obj == this)
            {
                return true;
            }
            return obj is ThreeDS1Result2 other &&                ((this.Cavv == null && other.Cavv == null) || (this.Cavv?.Equals(other.Cavv) == true)) &&
                ((this.CavvAlgorithm == null && other.CavvAlgorithm == null) || (this.CavvAlgorithm?.Equals(other.CavvAlgorithm) == true)) &&
                ((this.Eci == null && other.Eci == null) || (this.Eci?.Equals(other.Eci) == true)) &&
                ((this.ThreeDAuthenticatedResponse == null && other.ThreeDAuthenticatedResponse == null) || (this.ThreeDAuthenticatedResponse?.Equals(other.ThreeDAuthenticatedResponse) == true)) &&
                ((this.ThreeDOfferedResponse == null && other.ThreeDOfferedResponse == null) || (this.ThreeDOfferedResponse?.Equals(other.ThreeDOfferedResponse) == true)) &&
                ((this.Xid == null && other.Xid == null) || (this.Xid?.Equals(other.Xid) == true));
        }
        
        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"this.Cavv = {(this.Cavv == null ? "null" : this.Cavv)}");
            toStringOutput.Add($"this.CavvAlgorithm = {(this.CavvAlgorithm == null ? "null" : this.CavvAlgorithm)}");
            toStringOutput.Add($"this.Eci = {(this.Eci == null ? "null" : this.Eci)}");
            toStringOutput.Add($"this.ThreeDAuthenticatedResponse = {(this.ThreeDAuthenticatedResponse == null ? "null" : this.ThreeDAuthenticatedResponse)}");
            toStringOutput.Add($"this.ThreeDOfferedResponse = {(this.ThreeDOfferedResponse == null ? "null" : this.ThreeDOfferedResponse)}");
            toStringOutput.Add($"this.Xid = {(this.Xid == null ? "null" : this.Xid)}");
        }
    }
}